data_root:
  # KITTI sequences root
  data_root_folder: "/youtu_shuziren_qy_large/users/chadfu/datasets/kitti/dataset/sequences"
  #data_root_folder: "/home/fuchencan/datasets/KITTI/datasets/sequences"
extractor_config:
  seqs: ["00", "02", "05", "06", "07", "08"]
  # seqs: ["00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21"]
  pretrained_backbone_model: "./models/bevnet.ckpt"
  batch_num: 1

training_config:
  # KITTI sequences for training
  #training_seqs: ["11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21"]
  training_seqs: ["06"]
  # training log folder
  log_folder: "./log"
  # pretrained model
  pretrained_vlad_model: "/home/fuchencan/OverlapNetVLAD/log/fine/08291041.ckpt"
  pos_threshold: 10
  neg_threshold: 50
  batch_size: 2 
  epoch: 100000

test_config:
  # KITTI sequence 00 for evaluation
  seq: "08"
  # pretrained model
  test_overlap_model: "./models/overlap.ckpt"
  #test_vlad_model: "/home/fuchencan/OverlapNetVLAD/log/1610.ckpt"
  th_min: 0
  th_max: 10
  th_max_pre: 10
  skip: 50
  batch_num: 16

